# Generated by Django 5.1.6 on 2025-07-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='Product-Images')),
                ('category', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=5000)),
                ('code', models.CharField(default='000000', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
