# Generated by Django 5.1.6 on 2025-07-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
