# Generated by Django 5.1.6 on 2025-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=400)),
                ('cus_phone', models.CharField(max_length=500)),
                ('cus_email', models.EmailField(max_length=500)),
                ('cus_address', models.TextField(max_length=500)),
                ('cus_city', models.CharField(max_length=500)),
                ('cus_place', models.CharField(max_length=500)),
                ('cus_notes', models.TextField(max_length=2000)),
                ('date_of_register', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
