# Generated by Django 5.1.6 on 2025-07-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_alter_order_cus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cus_name',
            field=models.CharField(default='Someone', max_length=400),
            preserve_default=False,
        ),
    ]
