# Generated by Django 5.1.6 on 2025-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_alter_order_cus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cus_place',
            field=models.CharField(default='Not Know', max_length=500),
        ),
    ]
